version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt -t .
  build:
    commands:
      - echo "Running tests..."
      # pytest  # (optional, if you have tests)
      - echo "Build complete"
artifacts:
  files:
    - '**/*'